name: Release to NuGet

on:
 push:
    branches:
      - release


jobs:
  build:
    env:
     working-directory: ./UserAgentGenerator # choose your solution folder here
     
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    
    - name: Build
      run: dotnet build -c Release
      working-directory: ${{env.working-directory}}

    - name: Test
      run: dotnet test -c Release --no-build
      working-directory: ${{env.working-directory}}

    
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
      working-directory: ${{env.working-directory}}

    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      working-directory: ${{env.working-directory}}
